# docker-compose.test.yml

services:
  wa-tester:
    build: .
    container_name: wa-connection-tester
    restart: "no"
    # --- FIX: The user is now defined inside the Dockerfile, so we don't need this. ---
    # user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - wwebjs_auth_test_data:/data

volumes:
  wwebjs_auth_test_data:
