# docker-compose.test.yml

services:
  wa-tester:
    build: .
    container_name: wa-connection-tester
    restart: "no"
    # --- FIX: Run the container as the current host user ---
    # This ensures that any files created in the volume are owned by you,
    # not by the root user, which solves the permission errors.
    user: "${UID}:${GID}"
    volumes:
      - wwebjs_auth_test_data:/usr/src/app/wwebjs_auth_test

volumes:
  wwebjs_auth_test_data:
